title: 'PS-Group'
source:
destination: '_site'
url: 'http://ps-group.github.io'
github_username: ps-group
markdown: kramdown
highlighter: rouge

collections:
  opengl:
    output: true
    name: Курс по OpenGL
    permalink: '/opengl/:path'
  sfml:
    output: true
    permalink: '/sfml/:path'
  js:
    output: true
    permalink: '/js/:path'
  packman:
    output: true
    permalink: '/packman/:path'
  compilers:
    output: true
    permalink: '/compilers/:path'
  os:
    output: true
    permalink: '/os/:path'
defaults:
    - scope:
        type: opengl
      values:
        layout: article
    - scope:
        type: sfml
      values:
        layout: article
    - scope:
        type: js
      values:
        layout: article
    - scope:
        type: packman
      values:
        layout: article
    - scope:
        type: compilers
      values:
        layout: article
    - scope:
        type: os
      values:
        layout: article
