title: 'PS-Group'
description: 'Материалы для курсов в Институте Программных Систем и в Волгатехе'
source:
destination: '_site'
url: 'http://ps-group.github.io'
github_username: ps-group
markdown: kramdown
highlighter: rouge
email: sshambir@gmail.com

gems:
  - jekyll-redirect-from

collections:
  opengl:
    output: true
    name: Курс по OpenGL
    permalink: '/opengl/:path'
  sfml:
    output: true
    permalink: '/sfml/:path'
  js:
    output: true
    permalink: '/js/:path'
  compilers:
    output: true
    permalink: '/compilers/:path'
  os:
    output: true
    permalink: '/os/:path'
  cxx:
    output: true
    permalink: '/cxx/:path'
defaults:
    - scope:
        type: opengl
      values:
        layout: article
    - scope:
        type: sfml
      values:
        layout: article
    - scope:
        type: js
      values:
        layout: article
    - scope:
        type: packman
      values:
        layout: article
    - scope:
        type: compilers
      values:
        layout: article
    - scope:
        type: os
      values:
        layout: article
    - scope:
        type: cxx
      values:
        layout: article
